// @generated automatically by Diesel CLI.

diesel::table! {
    auctions (uuid) {
        uuid -> Text,
        auctioneer -> Text,
        profile_id -> Text,
        coop -> Nullable<Array<Nullable<Text>>>,
        start_time -> Timestamp,
        end_time -> Timestamp,
        item_name -> Text,
        item_uuid -> Nullable<Text>,
        item_lore -> Nullable<Text>,
        item_id -> Nullable<Text>,
        item_count -> Nullable<Int4>,
        item_damage -> Nullable<Int4>,
        enchantments -> Nullable<Array<Nullable<Text>>>,
        unbreakable -> Nullable<Bool>,
        price -> Int8,
        claimed -> Nullable<Bool>,
        tier -> Text,
        category -> Text,
        last_updated -> Timestamp,
        bin -> Nullable<Bool>,
        reforge -> Nullable<Text>,
        upgrade_level -> Nullable<Int4>,
        hot_potato_count -> Nullable<Int4>,
        recomb -> Nullable<Bool>,
        unlocked_gem_slots -> Nullable<Array<Nullable<Text>>>,
        slotted_gems -> Nullable<Array<Nullable<Text>>>,
        pet_active -> Nullable<Bool>,
        pet_type -> Nullable<Text>,
        pet_held_item -> Nullable<Text>,
        pet_exp -> Nullable<Int4>,
        pet_candy_used -> Nullable<Int4>,
        dungeon_item_level -> Nullable<Int4>,
        red_armor_coloring -> Nullable<Int4>,
        green_armor_coloring -> Nullable<Int4>,
        blue_armor_coloring -> Nullable<Int4>,
        anvil_uses -> Nullable<Int4>,
        pelts_earned -> Nullable<Int4>,
        champion_combat_xp -> Nullable<Int4>,
        farmed_cultivating -> Nullable<Int4>,
        compact_blocks -> Nullable<Int4>,
        hecatomb_s_runs -> Nullable<Int4>,
        expertise_kills -> Nullable<Int4>,
        runes -> Nullable<Array<Nullable<Text>>>,
    }
}
