-- Your SQL goes here
CREATE TABLE auctions (
  uuid text primary key,
  auctioneer text not null,
  profile_id text not null,
  coop text[],
  start_time timestamp not null,
  end_time timestamp not null,
  item_name text not null,
  item_uuid text,
  item_lore text,
  item_id text,
  item_count integer,
  item_damage integer,
  enchantments text[],
  unbreakable boolean default false,
  price bigint not null,
  claimed boolean default false,
  tier text not null,
  category text not null,
  last_updated timestamp not null,
  bin boolean default true,
  reforge text,
  upgrade_level integer,
  hot_potato_count integer,
  recomb boolean default false,
  unlocked_gem_slots text[],
  slotted_gems text[],
  pet_active boolean default false,
  pet_type text,
  pet_held_item text,
  pet_exp integer,
  pet_candy_used integer,
  dungeon_item_level integer,
  red_armor_coloring integer,
  green_armor_coloring integer,
  blue_armor_coloring integer,
  anvil_uses integer,
  pelts_earned integer,
  champion_combat_xp integer,
  farmed_cultivating integer,
  compact_blocks integer,
  hecatomb_s_runs integer,
  expertise_kills integer,
  runes text[]
)
